### ISSUE TITLE
System.IO.IOException during TryShadowPhotoID.

### ISSUE THREAD

**Issue by Cllyde** [Cllyde/iDoc#64]
An exception message similar to 
"System.IO.IOException: Target directory 'D:\BANK\IMG2\CIF\509745326\' does not exist
   at DataManager.HandlerManager.DelegateHandler.Call(Object[] Args)
   at WebAdminAccess.Images.SetInsitePhotoImage(Int32 CIF, Byte[] ImageData)
   at ASI.iDoc.Controllers.Image2ShadowController.TryShadowPhotoID(db_Document photoID, db_DocumentType photoIDDocType)" was found in the ASILog file when trying to upload a .tif file to update a photo id document type.

**Comment by Cllyde** [comment]
Fix was to create the CIF folder under the IMG2 folder. Once that CIF folder existed, the images were shadow copied correctly.
We also added permissions for "Bank Users" and "Everyone" to the IMG2 folder, but we think that since the CIF folder is usually created as part of the setup of Document Imaging, and it didn't exist in this case, insite will not create the folder, and we end up with the exception of "Target directory '' not found".
Another thing to check might be the Image2ShadowCopy setting in IDoc.config. It had a capital T in true, where in most other config files, it is all lowercase, like shown here.

`<add key="Image2ShadowCopy" value="true" />`
